### ISSUE TITLE
Torrent added but without trackers

### ISSUE THREAD

**Issue by zdecamp** [muriloportugal/DelugeAddTorrent#1]
As of about two weeks ago, when I download to deluge, the torrent is added to the queue, but there is no tracker info so they never start. I have tested on multiple sites to make sure it wasn't the site's magnet links themselves.

**Comment by muriloportugal** [comment]
> As of about two weeks ago, when I download to deluge, the torrent is added to the queue, but there is no tracker info so they never start. I have tested on multiple sites to make sure it wasn't the site's magnet links themselves.

Hi @zdecamp  
Could you please share the magnet link you are using?
If you copy the magnet link and paste manually in Deluge Web > Add button > Magnet Link, the download start?

**Comment by zdecamp** [comment]
> Hi @zdecamp Could you please share the magnet link you are using? If you copy the magnet link and paste manually in Deluge Web > Add button > Magnet Link, the download start?

Hey sorry for the delay, I've been pretty sick. I'm not sure what changed, because  had tried magnet links from a lot of different torrent sites, RARBG, tpbproxypirate, yts.mx and some private trackers, but I had the same issue with all of them. Today, I tried again, and it looks like things are working properly when adding. I didn't have a chance to copy the magnet link and try adding using the add button while the issue was still happening.

**Comment by muriloportugal** [comment]
@zdecamp i hope you are better now, about the issue i'll close it and if the problem come back please let me know.
